# Generated by Django 2.0.6 on 2018-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='url',
        ),
    ]
